
name: Code Review

on: [push, pull_request]

jobs:
  lint-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tools
        run: pip install flake8 black radon
      - name: Run flake8
        run: flake8 .
      - name: Run Black check
        run: black --check .
      - name: Run Radon CC
        run: radon cc . -s -n B
